language: cpp
sudo: required
services:
    - docker
dist: trusty
os: linux
cache:
  directories:
  - $HOME/.cache/bazel
install: skip
before_script:
    - cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt
jobs:
  include:
    - stage: lint
      env:
        - JOB=lint
      script:
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20181001_1754-ci
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"    
    - stage: build_and_test
      env:
        - JOB=cibuild
        - JOB=citest
      script:
        - ./docker/scripts/dev_start.sh -t dev-x86_64-20181001_1754-ci
        - ./apollo_docker.sh ${JOB}
        - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
        - rm -rf "/apollo/data/core"  
notifications:
    email:
        on_success: always
        on_failure: always
        
