language: cpp
sudo: required
services:
    - docker
dist: trusty
os: linux
env:
    - JOB=lint
    - JOB=cibuild
    - JOB=citest
cache:
  directories:
  - $HOME/.cache/bazel
install: skip
before_script:
    - cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt
script:
    - ./docker/scripts/dev_start.sh -t dev-x86_64-20180925_1415
    - ./apollo_docker.sh ${JOB}
    - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
    - rm -rf "/apollo/data/core"
notifications:
    email:
        on_success: change
        on_failure: always
