camera:
  viewAngle: 0.65
  Default:
    fov: 60
    near: 1
    far: 300
  Near:
    fov: 60
    near: 1
    far: 200
  Overhead:
    fov: 60
    near: 1
    far: 100
  Map:
    fov: 70
    near: 1
    far: 4000
  laneWidth: 4.5 # original 3.32
  laneWidthToViewDistanceRatio: 5
ground:
  defaults:
    mpp: 0.125
    xres: 8192
    yres: 8192
    xorigin: 4096
    yorigin: 4096
    type: default # default or tile
    tileRange: 4
  sunnyvale_big_loop:
    mpp: 0.125
    xres: 24576
    yres: 16384
    xorigin: 587392
    yorigin: 4140800
    type: default # default or tile
    tileRange: 4
planning:
  # The minimum interval between two consecutive
  minInterval: 0.1
  defaults:
    width: 1.4
  pathProperties:
    trajectory:
      optionName: 'showPlanningTrajectory'
      width: 0.8
      color: 0x01D1C1
      opacity: 0.65
      zOffset: 4
    planning_reference_line:
      optionName: 'showPlanningReference'
      width: 0.15
      color: 0x36A2EB
      opacity: 1
      zOffset: 7
    DpPolyPathOptimizer:
      optionName: 'showPlanningDpOptimizer'
      width: 0.4
      color: 0x8DFCB4
      opacity: 0.8
      zOffset: 6
    QpSplinePathOptimizer:
      optionName: 'showPlanningQpOptimizer'
      width: 0.65
      color: 0xd85656
      opacity: 0.8
      zOffset: 5
options:
  defaults:
    # side bar options
    showTasks: true
    showModuleController: false
    showMenu: false
    showRouteEditingBar: false
    showPOI: false
    enableAudioCapture: false
    showDataRecorder: false

    # task panel options
    showPNCMonitor: false
    enableSimControl: false
    lockTaskPanel: false
    showVideo: false

    # layer Menu options
    cameraAngle: Default
    showDecisionMain: true
    showDecisionObstacle: true
    showPlanningTrajectory: true
    showPlanningCar: false
    showPlanningReference: false
    showPlaningDpOptimizer: false
    showPlanningQpOptimizer: false
    showRouting: true
    showPerceptionLaneMarker: false
    showPointCloud: false
    showPredictionMajor: true
    showPredictionMinor: true
    showObstaclesVehicle: true
    showObstaclesPedestrian: true
    showObstaclesBicycle: true
    showObstaclesUnknownMovable: true
    showObstaclesUnknownUnmovable: true
    showObstaclesUnknown: true
    showObstaclesVirtual: false
    showObstaclesCipv: true
    showObstaclesVelocity: true
    showObstaclesHeading: true
    showObstaclesId: true
    showObstaclesInfo: true
    showPositionGps: false
    showPositionLocalization: true
    showMapCrosswalk: true
    showMapClearArea: true
    showMapJunction: false
    showMapLane: true
    showMapRoad: false
    showMapSignal: true
    showMapStopSign: true
    showMapSpeedBump: true
    showMapParkingSpace: true

navigation:
  # possible options: BaiduMap or GoogleMap
  map: "BaiduMap"

  # Google Map API: "https://maps.google.com/maps/api/js"
  # Baidu Map API: "https://api.map.baidu.com/api?v=3.0&ak=0kKZnWWhXEPfzIkklmzAa3dZ&callback=initMap"
  mapAPiUrl: "https://api.map.baidu.com/api?v=3.0&ak=0kKZnWWhXEPfzIkklmzAa3dZ&callback=initMap"

debug:
  # Turn this on for monitor related debugging
  autoMonitorMessage: false
  performanceMonitor: false
server:
  port: 8888
